import React from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import Index from "./pages/Index";
import NewStorySetup from "./pages/NewStorySetup";
import WritePad from "./pages/WritePad";
import NotFound from "./pages/NotFound";
import Landing from "./pages/Landing";
const queryClient = new QueryClient();
const App = () => /* @__PURE__ */ React.createElement(QueryClientProvider, { client: queryClient }, /* @__PURE__ */ React.createElement(TooltipProvider, null, /* @__PURE__ */ React.createElement(Toaster, null), /* @__PURE__ */ React.createElement(Sonner, null), /* @__PURE__ */ React.createElement(BrowserRouter, null, /* @__PURE__ */ React.createElement(Routes, null, /* @__PURE__ */ React.createElement(Route, { path: "/", element: /* @__PURE__ */ React.createElement(Landing, null) }), /* @__PURE__ */ React.createElement(Route, { path: "/dashboard", element: /* @__PURE__ */ React.createElement(Index, null) }), /* @__PURE__ */ React.createElement(Route, { path: "/new", element: /* @__PURE__ */ React.createElement(NewStorySetup, null) }), /* @__PURE__ */ React.createElement(Route, { path: "/write", element: /* @__PURE__ */ React.createElement(WritePad, null) }), /* @__PURE__ */ React.createElement(Route, { path: "*", element: /* @__PURE__ */ React.createElement(NotFound, null) })))));
export default App;
